### ISSUE TITLE
npm install not install a dependencies correctly

### ISSUE THREAD

**Issue by nantaphop** [tinytacoteam/zazu-clipboard#13]
Run update plugin and found following log from plugin debugger

```
ERROR: [08:05:09] [tinytacoteam/zazu-clipboard :Database]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/underscore/underscore.js'
{
  "block": "Database",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/underscore/underscore.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/underscore/underscore.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:05:09.050Z"
}

```

I also grep -r "underscore" in zazu-clipboard root directory to find where is it require underscore. 

```
node_modules/nedb/lib/cursor.js:  , _ = require('underscore')
node_modules/nedb/lib/datastore.js:  , _ = require('underscore')
node_modules/nedb/lib/indexes.js:  , _ = require('underscore')
node_modules/nedb/lib/model.js:  , _ = require('underscore')
node_modules/nedb/package.json:    "underscore": "~1.4.4"
node_modules/nedb/test/cursor.test.js:  , _ = require('underscore')
node_modules/nedb/test/db.test.js:  , _ = require('underscore')
node_modules/nedb/test/executor.test.js:  , _ = require('underscore')
node_modules/nedb/test/indexes.test.js:  , _ = require('underscore')
node_modules/nedb/test/model.test.js:  , _ = require('underscore')
node_modules/nedb/test/persistence.test.js:  , _ = require('underscore')
```

**Comment by nantaphop** [comment]
a lot of plugin also not install via npm install
```
ERROR: [08:33:59] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:59.485Z"
}
ERROR: [08:33:59] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:59.331Z"
}
ERROR: [08:33:59] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:59.213Z"
}
ERROR: [08:33:58] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:58.892Z"
}
ERROR: [08:33:58] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:58.799Z"
}
ERROR: [08:33:58] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:58.490Z"
}
ERROR: [08:33:58] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:58.315Z"
}
ERROR: [08:33:57] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:57.722Z"
}
ERROR: [08:33:57] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:57.124Z"
}
ERROR: [08:33:56] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:56.916Z"
}
ERROR: [08:33:56] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:56.672Z"
}
ERROR: [08:33:56] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:56.447Z"
}
ERROR: [08:33:55] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:55.797Z"
}
ERROR: [08:33:55] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:55.654Z"
}
ERROR: [08:33:55] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:55.500Z"
}
ERROR: [08:33:55] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:55.301Z"
}
ERROR: [08:33:55] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:55.248Z"
}
ERROR: [08:33:55] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:55.125Z"
}
ERROR: [08:33:54] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:54.483Z"
}
INFO: [08:33:54] [tinytacoteam/zazu-clipboard ]
scoping plugin
{
  "level": "info",
  "message": "scoping plugin",
  "plugin": "tinytacoteam/zazu-clipboard",
  "time": "2017-01-11T01:33:54.444Z"
}
ERROR: [08:33:54] [tinytacoteam/zazu-clipboard :searcher]
ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'
{
  "block": "searcher",
  "level": "error",
  "message": "ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
  "plugin": "tinytacoteam/zazu-clipboard",
  "stack": [
    "Error: ENOENT: no such file or directory, open '/Users/nantaphop/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/clone/clone.js'",
    "    at Error (native)",
    "    at Object.fs.openSync (fs.js:640:18)",
    "    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)",
    "    at Object.fs.readFileSync (fs.js:508:33)",
    "    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)",
    "    at Module._extensions..js (module.js:564:20)",
    "    at Object.require.extensions.(anonymous function) [as .js] (/Applications/Zazu.app/Contents/Resources/app.asar/node_modules/babel-register/lib/node.js:152:7)",
    "    at Module.load (module.js:473:32)",
    "    at tryModuleLoad (module.js:432:12)",
    "    at Function.Module._load (module.js:424:3)"
  ],
  "time": "2017-01-11T01:33:54.406Z"
}
```

**Comment by bayleedev** [comment]
Can you paste your zazu log into a gist?

It's located in `~/.zazu/log`.

What version of git do you have installed?

What os are you using?
