### ISSUE TITLE
clipboard plugin is crashing

### ISSUE THREAD

**Issue by amjith** [tinytacoteam/zazu-clipboard#9]
```
ERROR: [17:03:08][tinytacoteam/zazu-clipboard:searcher] 
Plugin failed to load
{
  "message": "Cannot find module 'clone'",
  "stack": [
    "Error: Cannot find module 'clone'",
    "    at Module._resolveFilename (module.js:440:15)",
    "    at Function.Module._resolveFilename (/Applications/Zazu.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)",
    "    at Function.Module._load (module.js:388:25)",
    "    at Module.require (module.js:468:17)",
    "    at require (internal/module.js:20:19)",
    "    at Object.<anonymous> (/Users/amjith/.zazu/plugins/tinytacoteam/zazu-clipboard/node_modules/color/index.js:2:13)",
    "    at Module._compile (module.js:541:32)",
    "    at Object.Module._extensions..js (module.js:550:10)",
    "    at Module.load (module.js:458:32)",
    "    at tryModuleLoad (module.js:417:12)",
    "    at Function.Module._load (module.js:409:3)",
    "    at Module.require (module.js:468:17)",
    "    at require (internal/module.js:20:19)",
    "    at Object.<anonymous> (/Users/amjith/.zazu/plugins/tinytacoteam/zazu-clipboard/src/lib/present.js:2:15)",
    "    at Module._compile (module.js:541:32)",
    "    at Object.Module._extensions..js (module.js:550:10)"
  ]
}
```

The module `clone` is required by `color`. I do have `clone` installed, but somehow it is not recognized when imported by `color`. 

Not sure how to fix this.

**Comment by bayleedev** [comment]
Is this on your work computer? I thought you fixed this before by wiping your `~/.zazu` directory?

Can you try reinstalling? I could remove the color dependency, but I'm curious why this happened twice with the same dependency. Other plugins with dependencies don't seem to have the same issue.

**Comment by bayleedev** [comment]
Actually are you using the latest zazu master? Gimmeh your log file! :D

**Comment by amjith** [comment]
I just git pulled the latest zazu and built a release and clipboard is behaving fine. If it misbehaves, I'll reopen then with the log file.
